import { db } from "@/db";
import { sql } from "drizzle-orm";

let schemaEnsured = false;

export async function ensureSchema() {
  if (schemaEnsured) return;

  try {
    // Add missing columns
    await db.execute(sql`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password" text`);
    await db.execute(sql`ALTER TABLE "games" ADD COLUMN IF NOT EXISTS "rules" text`);
    await db.execute(sql`ALTER TABLE "picks" ADD COLUMN IF NOT EXISTS "active_golfer_id" integer`);
    await db.execute(sql`ALTER TABLE "picks" ADD COLUMN IF NOT EXISTS "alternate_activated" boolean NOT NULL DEFAULT false`);
    await db.execute(sql`ALTER TABLE "picks" ADD COLUMN IF NOT EXISTS "earnings" numeric(12,2) DEFAULT '0'`);

    // Create announcements table if missing
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS "announcements" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "game_id" integer NOT NULL REFERENCES "games"("id") ON DELETE CASCADE,
        "author_id" text NOT NULL REFERENCES "users"("id"),
        "message" text NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
      )
    `);

    // Create password_reset_tokens table if missing
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "token" text NOT NULL UNIQUE,
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
      )
    `);

    schemaEnsured = true;
  } catch (err) {
    console.error("[ensureSchema]", err);
  }
}
