CREATE TABLE IF NOT EXISTS "custom_leaderboard_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_leaderboard_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"custom_leaderboard_id" integer NOT NULL,
	"user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "custom_leaderboard_shares" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_leaderboard_shares_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"custom_leaderboard_id" integer NOT NULL,
	"shared_with_user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "custom_leaderboards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_leaderboards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" integer NOT NULL,
	"owner_id" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "golfers" ADD COLUMN IF NOT EXISTS "world_ranking" integer;--> statement-breakpoint
ALTER TABLE "custom_leaderboard_members" ADD CONSTRAINT "custom_leaderboard_members_custom_leaderboard_id_custom_leaderboards_id_fk" FOREIGN KEY ("custom_leaderboard_id") REFERENCES "public"."custom_leaderboards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_leaderboard_members" ADD CONSTRAINT "custom_leaderboard_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_leaderboard_shares" ADD CONSTRAINT "custom_leaderboard_shares_custom_leaderboard_id_custom_leaderboards_id_fk" FOREIGN KEY ("custom_leaderboard_id") REFERENCES "public"."custom_leaderboards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_leaderboard_shares" ADD CONSTRAINT "custom_leaderboard_shares_shared_with_user_id_users_id_fk" FOREIGN KEY ("shared_with_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_leaderboards" ADD CONSTRAINT "custom_leaderboards_game_id_games_id_fk" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_leaderboards" ADD CONSTRAINT "custom_leaderboards_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_custom_lb_member_unique" ON "custom_leaderboard_members" USING btree ("custom_leaderboard_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_custom_lb_share_unique" ON "custom_leaderboard_shares" USING btree ("custom_leaderboard_id","shared_with_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_custom_lb_game" ON "custom_leaderboards" USING btree ("game_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_custom_lb_owner" ON "custom_leaderboards" USING btree ("owner_id");