-- Custom leaderboards migration
-- Run with: npx drizzle-kit push  (or execute manually)

CREATE TABLE IF NOT EXISTS "custom_leaderboards" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "game_id" integer NOT NULL REFERENCES "games"("id") ON DELETE CASCADE,
  "owner_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_custom_lb_game" ON "custom_leaderboards"("game_id");
CREATE INDEX IF NOT EXISTS "idx_custom_lb_owner" ON "custom_leaderboards"("owner_id");

CREATE TABLE IF NOT EXISTS "custom_leaderboard_members" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "custom_leaderboard_id" integer NOT NULL REFERENCES "custom_leaderboards"("id") ON DELETE CASCADE,
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "idx_custom_lb_member_unique" UNIQUE ("custom_leaderboard_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "custom_leaderboard_shares" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "custom_leaderboard_id" integer NOT NULL REFERENCES "custom_leaderboards"("id") ON DELETE CASCADE,
  "shared_with_user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "idx_custom_lb_share_unique" UNIQUE ("custom_leaderboard_id", "shared_with_user_id")
);
